sudo: required

language: python

services:
  - docker

install:
  - docker-compose --version

before_script:
  - docker-compose up --build -d

script:
  - make style
  - make test


after_script:
  - docker-compose down
