sudo: required

language: python

services:
  - docker

install:
  - docker-compose --version

before_script:
  - docker-compose up --build -d

script:
  - docker-compose run web python3 ./manage.py test

after_script:
  - docker-compose down