version: '3'

services:
    #db:
  #  image: postgres
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    #depends_on:
    #  - db

  tester:
    build: .
    #command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
     - selenium

  #selenium:
  #  image: selenium/standalone-chrome
  #  container_name: selenium
  #  ports:
  #    - "4444:4444"
  #  expose:
  #    - "4444"
  #  depends_on:
  #    - web


  selenium:
    image: selenium/hub
    container_name: selenium
    ports:
      - "4444:4444"
    expose:
      - "4444"
    depends_on:
      - web

  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - selenium

  firefox:
    image: selenium/node-firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium
      - HUB_PORT_4444_TCP_PORT=4444
    depends_on:
      - selenium
